import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/theme-provider'
import Sidebar from '@/components/sidebar'
import Headbar from '@/components/headbar'
import StudentMode from '@/lib/mode/student-mode'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className='hidden md:flex'>
              <Sidebar />
            </div>
            <Headbar />
           
            {children}
            
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
